"""initial tables: users, companies, valuations

Revision ID: 8cef17331f60
Revises: 
Create Date: 2026-04-12 15:07:23.921025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cef17331f60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('revenue_status', sa.String(length=50), nullable=False),
    sa.Column('current_revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('last_round_date', sa.Date(), nullable=True),
    sa.Column('last_round_valuation', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('last_round_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('last_round_investor', sa.String(length=255), nullable=True),
    sa.Column('projections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auditor_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('valuations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('primary_method', sa.String(length=50), nullable=False),
    sa.Column('fair_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fair_value_low', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fair_value_high', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('data_completeness', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('method_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audit_trail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valuations')
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
